pixit/my_app/urls.py
from django.urls import path
from . import views


app_name= 'my_app'

urlpatterns=[
    path("",views.IntroPageView, name='intro'),
    path("home/", views.HomePageView, name='homepage'),
    path("loading/",views.LoadView, name='loading'),
    path('result/',views.ResultView, name='result'),
    path('sample/', views.ExampleView, name='sample'),
    path('about/',views.AboutView, name='about')
    

]

pixit/pixit/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('my_app/', include('my_app.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pixit/my_app/models.py
from django.db import models

# Create your models here.
class mydata(models.Model):
    image= models.ImageField(upload_to="touse/images", default='')

pixit/my_app/views.py
from django.shortcuts import render
from . import models
from django.http import JsonResponse
import cv2
import numpy as np
from django.urls import reverse
from PIL import Image
from django.conf import settings
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import FormView


def square_image(inpath, outpath):
    img = cv2.imread(inpath)

    height, width = img.shape[:2]

    max_dim = max(width, height)

    square_canvas = np.ones((max_dim, max_dim, 3), dtype=np.uint8) * 255

    paste_x = (max_dim - width) // 2
    paste_y = (max_dim - height) // 2

    square_canvas[paste_y:paste_y+height, paste_x:paste_x+width] = img

    cv2.imwrite(outpath, square_canvas)

num=2
gnum=32

# Create your views here.
def IntroPageView(request):
    return render(request, 'my_app/example.html')



def HomePageView(request):
    if request.method == 'POST':
        if 'imageInput' in request.FILES:
            image_file = request.FILES['imageInput']
            
            
            with open('media/touse/images/image.png', 'wb') as f:
                for chunk in image_file.chunks():
                    f.write(chunk)

            
            inpath = "media/touse/images/image.png"
            outpath = "media/touse/images/image.png"
            square_image(inpath, outpath)

            
            num=2
            gnum=32
            for i in range(6):
                img = cv2.imread(outpath)
                
                height, width = img.shape[:2]

                temp = cv2.resize(img, (num, num), interpolation=cv2.INTER_CUBIC)
                img = cv2.resize(temp, (640, 640), interpolation=cv2.INTER_NEAREST)

                grid_spacing = gnum * 10  # Adjust this value as needed
                for y in range(0, 640, grid_spacing):
                    cv2.line(img, (0, y), (640, y), (0, 0, 0), 1)
                for x in range(0, 640, grid_spacing):
                    cv2.line(img, (x, 0), (x, 640), (0, 0, 0), 1)


                output_path = f"my_app/static/my_app/output{i}.png"
                cv2.imwrite(output_path, img)

                num *= 2
                gnum /= 2
                gnum=int(gnum)
                #pixleit(num,gnum)
            return HttpResponseRedirect(reverse('my_app:loading'))

    return render(request, 'my_app/home.html')

def LoadView(request):
    return render(request,'my_app/loading.html')

def ResultView(request):
    return render(request,'my_app/result.html')

def ExampleView(request):
    return render(request, 'my_app/sample.html')

def AboutView(request):
    return render(request,'my_app/about.html')


pixit/my_app/templates/my_app/about.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>About Us</title>
  <link rel="stylesheet" href="https://pyscript.net/releases/2024.1.1/core.css" />
    <script type="module" src="https://pyscript.net/releases/2024.1.1/core.js"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <link rel="stylesheet" href={% static "my_app/styles.css"%}>
  <style>
    body {
      font-family: Arial, sans-serif;
      margin: 0;
      padding: 0;
      background-color: black;
      color: yellow;
    }

    .container {
      max-width: 1200px;
      margin: 0 auto;
      padding: 50px;
      text-align: center;
    }

    h1, h2 {
      color: yellow;
    }

    p {
      font-size: 18px;
      line-height: 1.6;
      margin-bottom: 20px;
    }

    .section {
      margin-bottom: 50px;
      display: flex;
      flex-direction: row;
      align-items: center;
      justify-content: center;
    }

    .section:nth-child(odd) .text {
      order: 1;
    }

    .section:nth-child(odd) img {
      margin-right: 20px;
    }

    .section:nth-child(even) img {
      margin-left: 20px;
    }

    .section img {
      max-width: 400px;
      border-radius: 10px;
      box-shadow: 0 0 20px rgba(244, 178, 72, 0.5);
    }

    .text {
      flex: 1;
      text-align: left;
    }
  </style>
</head>
<body>
    <section id="header">
        <a href={% url 'my_app:homepage' %}><img src= {% static "my_app/logop.png"%} class="logo" alt=""></a>
        <div>
            <ul id="navbar">
                <li><a href={% url 'my_app:homepage' %}>Home</a></li>
                <li><a href={% url 'my_app:sample' %}>Examples</a></li>
                <li><a class ="active" href={% url 'my_app:about' %}>About</a></li>

            </ul>
        </div>
    </section>

  <div class="container">
    <section class="section" id="section1">
      <img src={% static "my_app/ghost.jpg"%} alt="About Us Image" style="height: 500px; width: auto;">
      <div class="text">
        <h1 style="color: wheat; font-weight: bold;
        font-style: italic; text-decoration: underline;">The Story Behind Pixit</h1>
        <p style="
        color: tan;
    ">As an artist, I struggled to find the pixel art I needed. While conventional images were easy to find, the specific pixelated designs I wanted were hard to come by. This led me to develop an application that seamlessly transforms standard images into pixel art. It was a creative solution to a common problem in the artistic community, simplifying the process of accessing and manipulating visual content.</p>      </div>
    </section>
    
    <section class="section" id="section2">
      <div class="text" style="color: tan; font-size: large;">
        <h1 style="color: wheat; font-weight: bold;
        font-style: italic; text-decoration: underline;">Technologies Utilized:</h1>
        <p style="color: tan;"><ul style="color: tan;">
           <li>Python programming language</li> 
           <li>OpenCV library</li> 
            <li>Django web framework</li>
            <li>HTML</li>
            <li>CSS</li>
            <li>Bootstrap framework</li>
            <li>JavaScript</li>
            <li>Procreate (for design and artwork)</li>
            <li>Jinja</li>
            <li>Linode Hosting Platform</li>
            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
        </ul>
            This comprehensive blend of technologies and tools enabled the development of a dynamic and visually appealing website, seamlessly integrating advanced functionalities for pixel art transformation.</p>
      </div>
      <img src={% static "my_app/fullstack.jpeg"%} alt="Our Mission Image" style="width: 800px; height: auto;">
    </section>

    <section class="section" id="section3">
      
      <div class="text">
        <h1 style="color: wheat; font-weight: bold;
        font-style: italic; text-decoration: underline; text-align: center;">Get In Touch</h1>
        <p style="color: tan; font-size: large; text-align: center;">If you have any inquiries,suggestions, feedback, or collaboration opportunities, feel free to reach out. I'm always eager to connect with fellow enthusiasts and professionals.

            You can contact me via email at <a href="https://mail.google.com/mail/?view=cm&fs=1&to=agrawalutk.26@gmail.com">agrawalutk.26@gmail.com</a>
            or through the contact form on this website. Looking forward to hearing from you!</p>
      </div>
    </section>
  </div>
</body>
</html>

pixit/my_app/templates/my_app/example.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Auto Play Video</title>
<style>
  body, html {
    margin: 0;
    padding: 0;
    height: 100%;
    overflow: hidden;
  }
  #video-container {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    overflow: hidden;
  }
  video {
    width: auto;
    height: 100%;
  }
</style>
</head>
<body>
  <div id="video-container">
    <video autoplay muted id="myVideo">
      <source src={% static "my_app/Introf2.mp4" %} type="video/mp4">
      Your browser does not support the video tag.
    </video>
  </div>

  <script>
    const video = document.getElementById('myVideo');

    // Add event listener for when the video ends
    video.addEventListener('ended', function() {
      // Redirect to sec.html
    window.location.href = 'home/';  
    });
  </script>
</body>
</html>

pixit/my_app/templates/my_app/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://pyscript.net/releases/2024.1.1/core.css" />
    <script type="module" src="https://pyscript.net/releases/2024.1.1/core.js"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <link rel="stylesheet" href={% static "my_app/stylee.css"%}>
    <style>
        body {
            background-image: url("{% static "my_app/pixitbg.png" %}");
            height: 125px;
            background-position: center;
            
             /* Adjust as needed */
            /* You can add more background properties here */
        }
    </style>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    <section id="header">
        <a href={% url 'my_app:homepage' %}><img src= {% static "my_app/logop.png"%} class="logo" alt=""></a>
        <div>
            <ul id="navbar">
                <li><a  class ="active" href={% url 'my_app:homepage' %}>Home</a></li>
                <li><a href={% url 'my_app:sample' %}>Examples</a></li>
                <li><a href={% url 'my_app:about' %}>About</a></li>

            </ul>
        </div>
    </section>

    <form method="POST" enctype="multipart/form-data">
        {%csrf_token%}
    <div class="card text-center mb-3" style="width: 25rem;">
        <div class="card-body">
          <h5 class="card-title">Welcome to Pixit</h5>
          <p class="card-text">Select your image by clicking the button below and see the magic happen...</p>
          <input type="file" class="Check" id="imageInput" name="imageInput" accept="image/*" style="align-items: center;position: absolute;left: 89px;top: 110px;color: tan;">          <br>
          <input type="submit" class="btn btn-primary" value="Get Started">
        </div>
      </div>
    </form>
    


</body>
</html>

pixit/my_app/templates/my_app/loading.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Auto Play Video</title>
<style>
  body, html {
    margin: 0;
    padding: 0;
    height: 100%;
    overflow: hidden;
  }
  #video-container {
    width: 100%;
    height: 100vh; /* Set the height to 100% of the viewport height */
    display: flex;
    justify-content: center;
    align-items: center;
  }
  video {
    height: 100%; /* Set the height to 100% of the container's height */
    width: auto; /* Let the width adjust automatically to maintain aspect ratio */
  }
</style>
</head>
<body>
  <div id="video-container">
    <video autoplay muted id="myVideo" onended="videoEnded()">
      <source src="{% static "my_app/load.mp4" %}" type="video/mp4">
      Your browser does not support the video tag.
    </video>
  </div>

  <script>
    const video = document.getElementById('myVideo');
    let loopCount = 0;

    function videoEnded() {
      loopCount++;

      // Check if loopCount is less than 3, if so, replay the video
      if (loopCount < 3) {
        video.play();
      } else {
        // Redirect to sec.html after the third loop
        window.location.href = '/my_app/result/';
      }
    }
  </script>
</body>
</html>

pixit/my_app/templates/my_app/result.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://pyscript.net/releases/2024.1.1/core.css" />
    <script type="module" src="https://pyscript.net/releases/2024.1.1/core.js"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <link rel="stylesheet" href={% static "my_app/stylee.css"%}>
    <style>
        body {
            background-image: url("{% static "my_app/pixitbg.png" %}");
            height: 125px;
            
            background-position: center;
            
             /* Adjust as needed */
            /* You can add more background properties here */
        }
    </style>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        #carouselExampleIndicators .carousel-inner {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100%;
        }

        .carousel-item {
            text-align: center;
        }

        .carousel-item img {
            max-width: 70%;
            height: auto;
        }
    </style>
</head>

<body>
   
    <section id="header">
        <a href={% url 'my_app:homepage' %}><img src= {% static "my_app/logop.png"%} class="logo" alt=""></a>
        <div>
            <ul id="navbar">
                <li><a  class ="active" href={% url 'my_app:homepage' %}>Home</a></li>
                <li><a href={% url 'my_app:sample' %}>Examples</a></li>
                <li><a href={% url 'my_app:about' %}>About</a></li>
            </ul>
        </div>
    </section>
    
   
    <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="3" aria-label="Slide 4"></button>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="4" aria-label="Slide 5"></button>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="5" aria-label="Slide 6"></button>
        </div>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src={% static "my_app/output0.png"%} class="d-block" alt="..." style="
                    padding: -91px;
                    margin: 17px;
                    height: 460px;
                    width: auto;
                    position: relative;
                    left: -234px;
                    top: 13px;
                ">
            </div>
            <div class="carousel-item">
                <img src={% static "my_app/output1.png"%} class="d-block" alt="..." style="
                    padding: -91px;
                    margin: 17px;
                    height: 460px;
                    width: auto;
                    position: relative;
                    left: -234px;
                    top: 13px;
                ">
            </div>
            <div class="carousel-item">
                <img src={% static "my_app/output2.png"%} class="d-block" alt="..." style="
                    padding: -91px;
                    margin: 17px;
                    height: 460px;
                    width: auto;
                    position: relative;
                    left: -234px;
                    top: 13px;
                ">
            </div>
            <div class="carousel-item">
                <img src={% static "my_app/output3.png"%} class="d-block" alt="..." style="
                    padding: -91px;
                    margin: 17px;
                    height: 460px;
                    width: auto;
                    position: relative;
                    left: -234px;
                    top: 13px;
                ">
            </div>
            <div class="carousel-item">
                <img src={% static "my_app/output4.png"%} class="d-block" alt="..." style="
                    padding: -91px;
                    margin: 17px;
                    height: 460px;
                    width: auto;
                    position: relative;
                    left: -234px;
                    top: 13px;
                ">
            </div>
            <div class="carousel-item">
                <img src={% static "my_app/output5.png"%} class="d-block" alt="..." style="
                    padding: -91px;
                    margin: 17px;
                    height: 460px;
                    width: auto;
                    position: relative;
                    left: -234px;
                    top: 13px;
                ">
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
    
    

</body>
</html>

pixit/my_app/templates/my_app/sample.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <link rel="stylesheet" href={% static "my_app/styleee.css"%}>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
   
    <section id="header">
        <a href={% url 'my_app:homepage' %}><img src= {% static "my_app/logop.png"%} class="logo" alt=""></a>
        <div>
            <ul id="navbar">
                <li><a href={% url 'my_app:homepage' %}>Home</a></li>
                <li><a class ="active" href={% url 'my_app:sample' %}>Examples</a></li>
                <li><a href={% url 'my_app:about' %}>About</a></li>
            </ul>
        </div>
    </section>

    <section id="cardi">
    <div class="card" style="width: 18rem;">
        <img src={% static "my_app/heart.png"%} class="card-img-top" alt="...">
        <div class="card-body">
          <p class="card-text">INPUT</p>
        </div>
      </div>
    </section>

    <section id="cardo1">
      <div class="card" style="width: 18rem;">
        <img src={% static "my_app/o11.png"%} class="card-img-top" alt="...">
        <div class="card-body">
          <p class="card-text">OUTPUT 1</p>
        </div>
      </div>
    </section>

    <section id="cardo2">
        <div class="card" style="width: 18rem;">
          <img src={% static "my_app/o12.png"%} class="card-img-top" alt="...">
          <div class="card-body">
            <p class="card-text">OUTPUT 2</p>
          </div>
        </div>
      </section>

      <section id="cardo3">
        <div class="card" style="width: 18rem;">
          <img src={% static "my_app/o13.png"%} class="card-img-top" alt="...">
          <div class="card-body">
            <p class="card-text">OUTPUT 3</p>
          </div>
        </div>
      </section>

      <section id="cardo4">
        <div class="card" style="width: 18rem;">
          <img src={% static "my_app/o14.png"%} class="card-img-top" alt="...">
          <div class="card-body">
            <p class="card-text">OUTPUT 4</p>
          </div>
        </div>
      </section>

      <section id="cardo5">
        <div class="card" style="width: 18rem;">
          <img src={% static "my_app/o15.png"%} class="card-img-top" alt="...">
          <div class="card-body">
            <p class="card-text">OUTPUT 5</p>
          </div>
        </div>
      </section>

      <section id="cardo6">
        <div class="card" style="width: 18rem;">
          <img src={% static "my_app/o16.png"%} class="card-img-top" alt="...">
          <div class="card-body">
            <p class="card-text">OUTPUT 6</p>
          </div>
        </div>
      </section>

</body>
</html>